services:
  - type: web
    name: sistema-pedidos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p 10000 sistema.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sistema.settings
      - key: SECRET_KEY
        value: tu_clave_secreta
      - key: ALLOWED_HOSTS
        value: sistema-pedidos.onrender.com
    scripts:
      postinstall: ./render-build.sh


