services:
  - type: web
    name: sistema-pedidos
    env: python
    rootDir: sistema_pedidos
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p 10000 sistema.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sistema.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: tu-clave-secreta
      - key: ALLOWED_HOSTS
        value: sistema-pedidos.onrender.com