# Generated by Django 5.2 on 2025-05-21 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='personalizacion',
        ),
        migrations.CreateModel(
            name='PersonalizacionCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizacion', to='mi_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizacionOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='mi_app.personalizacioncampo')),
            ],
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='opciones_seleccionadas',
            field=models.ManyToManyField(blank=True, to='mi_app.personalizacionopcion'),
        ),
    ]
