# Generated by Django 5.2.1 on 2025-05-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='opciones_seleccionadas',
            field=models.ManyToManyField(blank=True, to='mi_app.personalizacionopcion'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.producto'),
        ),
    ]
