# Generated by Django 5.2 on 2025-05-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_remove_pedidoproducto_personalizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizacioncampo',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='campos_personalizacion',
            field=models.ManyToManyField(blank=True, related_name='productos', to='mi_app.personalizacioncampo'),
        ),
    ]
